import Head from 'next/head'
import Image from 'next/image'
import BotaoLink from '../src/components/BotaoLink'
import styles from '../styles/Home.module.css'
import banner from '../public/images/banner.jpg'
import Link from 'next/link'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Home | Alura Geek</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.banner}>
					<div className={styles.bannerInfo}>
						<h1>Dezembro Promocional</h1>
						<h3>Produtos selecionados com 30% de desconto!</h3>
						<BotaoLink href='/search/?category=console' filled>
							Ver consoles
						</BotaoLink>
					</div>
				</div>
				<div className={styles.categoryList}>
					<section className={styles.categoryHead}>
						<h1>Star Wars</h1>
						<Link href="/search/?category=star_wars">
							Mostrar tudo →
						</Link>
					</section>
				</div>
			</main>


		</div>
	)
}
